services:
  app:
    container_name: zapiet-pickup-delivery
    build:
      context: .
    ports:
      - "3006:3000"
    env_file:
      - .env
    environment:
      SHOPIFY_APP_URL: "https://zapiet.spfmktplace.tech.siwon.ca"
      DATABASE_URL: "file:dev.sqlite"
    volumes:
      - db_data:/app/prisma
    restart: unless-stopped

volumes:
  db_data:
