# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19fd58c59819f294ed3dd0cbfeb38047"
name = "zapiet-pickup-delivery"
application_url = "https://zapiet.spfmktplace.tech.siwon.ca"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders_create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/orders_updated"
  topics = [ "orders/updated" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_locations,read_shipping,write_shipping,read_customers,read_delivery_customizations,write_delivery_customizations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://zapiet.spfmktplace.tech.siwon.ca/auth/callback",
  "https://zapiet.spfmktplace.tech.siwon.ca/auth/shopify/callback",
  "https://zapiet.spfmktplace.tech.siwon.ca/api/auth/callback",
]

[app_proxy]
url = "https://zapiet.spfmktplace.tech.siwon.ca/api/widget-data"
subpath = "zapiet"
prefix = "apps"
