# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b7173c2389e0200edf0d9a591334e456"
application_url = "https://zapiet.spfmktplace.tech.siwon.ca"
embedded = true
name = "zapiet-pickup-delivery"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_delivery_customizations,read_locations,read_orders,read_shipping,write_delivery_customizations,write_orders,write_products,write_shipping"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://zapiet.spfmktplace.tech.siwon.ca/auth/callback",
  "https://zapiet.spfmktplace.tech.siwon.ca/auth/shopify/callback",
  "https://zapiet.spfmktplace.tech.siwon.ca/api/auth/callback"
]

[app_proxy]
url = "https://zapiet.spfmktplace.tech.siwon.ca/api/widget-data"
subpath = "zapiet"
prefix = "apps"
